"""Add CommunityJoinRequest

Revision ID: dd199c41822d
Revises: 5eb1fce07ae8
Create Date: 2026-07-09 20:56:34.073286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd199c41822d'
down_revision: Union[str, Sequence[str], None] = '5eb1fce07ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_join_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='joinrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_join_requests_community_id'), 'community_join_requests', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_join_requests_user_id'), 'community_join_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_join_requests_user_id'), table_name='community_join_requests')
    op.drop_index(op.f('ix_community_join_requests_community_id'), table_name='community_join_requests')
    op.drop_table('community_join_requests')
    op.execute("DROP TYPE joinrequeststatus")
    # ### end Alembic commands ###
