"""Update Notification model

Revision ID: fdec9410c2a4
Revises: 0643e81d8327
Create Date: 2026-07-14 11:11:27.555226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdec9410c2a4'
down_revision: Union[str, Sequence[str], None] = '0643e81d8327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('actor_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=False, server_default='system'))
    op.add_column('notifications', sa.Column('entity_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'actor_id')
    # ### end Alembic commands ###
